### Hypothesis :
- An assumption

1. Asssumption 1 : Avg age of M & F at innomatics is same.
2. Assumption 2 : M & F Proportion is different.
- This two are the conclusions of inferencial stats.

### Types of Hypothesis :
1. Null Hypothesis (H0) --> No change, established fact.
2. Alternate Hypothesis (H1) --> Change, Comparision...

**Note :** We have to test that the sample we have chosen provide us sufficient evidence to accept/regret H0.

**Rules :**
1. p_value < alpha --> Reject H0
2. p_value > alpha --> Accept H0

**Hypothesis Testing :**
1. Mean :
   + 1 sample with benchmark : ttest_1samp
   + 2 sample mean : ttest_ind
   + same sample before & after : ttest_rel
   + more than 2 sample mean : Anova
2. Proportion :
   + 1 proportion : 1 proportion 2-test
   + 2 proportion : 2 proportion 2-test
3. Categorical :
   + Chi-Square

#### Steps :
1. Define Hypothesis :H0 or H1
2. Consider alpha :0.05
3. Choose the statistical test
4. Compare p_value with alpha value : accept or Reject

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

In [7]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
sample = df.sample(frac=0.2)
sample.head()

    total_bill   tip     sex smoker   day    time  size
98       21.01  3.00    Male    Yes   Fri  Dinner     2
82       10.07  1.83  Female     No  Thur   Lunch     1
13       18.43  3.00    Male     No   Sun  Dinner     4
79       17.29  2.71    Male     No  Thur   Lunch     2
54       25.56  4.34    Male     No   Sun  Dinner     4

In [9]:
len(sample)

49

In [14]:
print('Sample of mean :',round(sample['total_bill'].mean(),2))

Sample of mean : 19.23

In [13]:
print('Population of mean :',round(df['total_bill'].mean(),2))

Population of mean : 19.79

**Infer :** Based on sample mean, we can assume that avg total bill for all customers is 19 USD.

#### Hypothesis
- H0 : Population mean is 19.
- H1 : Population mean is not 19.

- Consider alpha value is 0.05
- Because we have 1 sample and benchmark 19:ttest_1samp

In [12]:
from scipy.stats import ttest_1samp

In [19]:
#method 1
result=ttest_1samp(sample['total_bill'],popmean=19.7)

In [23]:
result.pvalue

np.float64(0.7172144318857667)

In [32]:
#method 2
t_stat, p_value = ttest_1samp(sample['total_bill'],popmean=19.7)
p_value

np.float64(0.7172144318857667)

In [31]:
p_value

np.float64(0.7172144318857667)

In [50]:
if p_value < 0.05:
    print('Reject H0')
else:
    print('Accept H1')

Accept H1

**Take two sample from the same data**
- H0 Mean of both sample is same
- H1 Mean of both sample is different

- Consider alpha : 0.05
  
**Ans :** We can use ttest_ind : Be are comparing two groups

In [36]:
from scipy.stats import ttest_ind

In [37]:
s1 = df.sample(frac=0.2)
s1.head()

     total_bill   tip     sex smoker  day    time  size
26        13.37  2.00    Male     No  Sat  Dinner     2
158       13.39  2.61  Female     No  Sun  Dinner     2
217       11.59  1.50    Male    Yes  Sat  Dinner     2
75        10.51  1.25    Male     No  Sat  Dinner     2
174       16.82  4.00    Male    Yes  Sun  Dinner     2

In [38]:
s2 = df.sample(frac=0.2)
s2.head()

     total_bill   tip     sex smoker   day    time  size
169       10.63  2.00  Female    Yes   Sat  Dinner     2
84        15.98  2.03    Male     No  Thur   Lunch     2
200       18.71  4.00    Male    Yes  Thur   Lunch     3
56        38.01  3.00    Male    Yes   Sat  Dinner     4
157       25.00  3.75  Female     No   Sun  Dinner     4

In [39]:
display(len(s1))
display(len(s2))

49

49

In [41]:
print('Sample of mean :',round(s1['total_bill'].mean(),2))
print('Population of mean :',round(df['total_bill'].mean(),2))

Sample of mean : 19.24
Population of mean : 19.79

In [42]:
print('Sample of mean :',round(s2['total_bill'].mean(),2))
print('Population of mean :',round(df['total_bill'].mean(),2))

Sample of mean : 18.93
Population of mean : 19.79

In [49]:
#method 1
t_stat, p_value = ttest_ind(s1['total_bill'],s2['total_bill'])
if p_value < 0.05:
    print('Reject H0')
else:
    print('Accept H1')

Accept H1

### Error Types
1. Type 1 : H0 true, Still regected.
3. Type 2 : H0 False, still accepted.

### Hypothesis Test
1. parametric (Mean, Proportion) - Normal Data ---> More accurate result **EX :** ttest, Anova.. - Sample Age
2. Non Parametric (Rank, Ordered) - Skewed Data ---> Less accurate result **EX :** mamwhitneyu, Chi Square - Sample Ratios(1-5)

1. Parametric : from scipy.stats import ttest_ind
2. Non Parametric : from scipy.stats import mamwhitneyu

### Hypothesis Cond..

In [3]:
# H0: Both group has similar distribution
g1 = [1,2,2,2,3,4]
g2 = [3,3,4,4,4,4]
from scipy.stats import mannwhitneyu

m_stats,pvalue=mannwhitneyu(g1,g2)
if pvalue<0.05:
    print("Reject the Null Hypothesis")
else:
    print("Accept the Null Hypothesis")

Reject the Null Hypothesis