In [2]:
TE={'H','T'}
FE={'H'}
p_h=len(FE)/len(TE)
print(f'Probability of getting Head : {p_h}')

Probability of getting Head : 0.5

In [3]:
import numpy as np

In [5]:
ss=np.random.choice(['H','T'])
print(f'Probability of getting Head : {len(ss)/2}')

Probability of getting Head : 0.5

In [6]:
ss=np.random.choice(['H','T'])
print(f'Probability of getting random event : {ss}')

Probability of getting random event : H

In [17]:
#simulating 1000 events
li=[np.random.choice(['H','T']) for i in range(1000)]
li

[np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('H'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('T'),
 np.str_('H'),
 np.str_('H'),
 np.str_('H')]

In [18]:
c=0
for i in li:
    if i=='H':
        c+=1
print('Probability of getting Head :',c/len(li))

Probability of getting Head : 0.499

In [19]:
import pandas as pd

In [20]:
df=pd.DataFrame({
    'Outcome':[np.random.choice(['H','T']) for i in range(1000)]
})
df

    Outcome
0         T
1         H
2         T
3         T
4         H
..      ...
995       T
996       T
997       H
998       H
999       H

[1000 rows x 1 columns]

In [22]:
# probability of getting head
fe=df[df['Outcome']=='H']
te=df
p=len(fe)/len(te)
print('Probability of getting Head :',p)

Probability of getting Head : 0.484

In [31]:
df1=pd.DataFrame({
    'customer_id':list(range(100,1000)),
    'loan_amount':np.random.randint(100000,1000000,size=(900)),
    'status':[np.random.choice(['Fraud','Not Fraud']) for i in range(900)]
})
df1

     customer_id  loan_amount     status
0            100       753476  Not Fraud
1            101       311050  Not Fraud
2            102       964159  Not Fraud
3            103       744221      Fraud
4            104       838817      Fraud
..           ...          ...        ...
895          995       529018      Fraud
896          996       165043      Fraud
897          997       262278  Not Fraud
898          998       221751      Fraud
899          999       236217      Fraud

[900 rows x 3 columns]

In [39]:
fe=df1[df1['status']=='Fraud']
te=df1
p=len(fe)/len(te)
print('Probability of getting next customer is Fraud is :',round(p,2))

Probability of getting next customer is Fraud is : 0.49

### Axioms (Rules):
1. Probability cannot be negative.
2. Probability can only lie b/w 0 and 1.
3. Probability of all possible events is 1.
4. Complimentary probability = 1-p(A)
5. Additive Rule : one experiment multiple outcome.
   1. (Mutual Exclusive Event) : Does not effect each other. p(A or B) = P(A) + p(B)
   2. (Non Mutual Exclusive Event) : Does effect each other. p(A or B) = P(A) + p(B) - P(A n B)
6. Multiplicative Rule :
   1. (Independent Event) : One event cannot affect second means Probability of second event is same. P(A and B) = P(A) * P(B)
   2. (Dependent Event) :Reduce the Probability of second event. P(A and B) = P(A) * P(B/A)

# 5G, 4R, 3B
g=5
r=4
b=3
p(g or r or b) = 5/12 + 4/12 + 3/12